### ISSUE TITLE
This method signature doesn't exist: Matrix.Factory.linkToJDBC(host, port, db, table, user, password)

### ISSUE THREAD

**Issue by ghost** [ujmp/universal-java-matrix-package#10]
The main page implies that our access to databases is automagic - we just set them up, and UJMP handles the rest for us transparently. The truth is far from that... we have to create our own database, populate it with our own data (after hours of reading javadocs), and finally, maybe, hopefully, UJMP will actually be able to reference the data in the database.

**Comment by holger-arndt** [comment]
You're right. Please use Matrix.Factory.importFromJDBC(DBType type, String host, int port, String database, String sqlStatement, String username, String password) instead.
