### ISSUE TITLE
'mvn install' fails on Win10 Java8 EclipseNeon

### ISSUE THREAD

**Issue by bigerl** [ujmp/universal-java-matrix-package#13]
org.ujmp.core.util.UJMPFormat imports com.sun.istack.internal.NotNull that is not used in the class and prevents maven from building successfully. It should probably be removed.
See http://stackoverflow.com/questions/1834826/it-is-a-bad-practice-to-use-suns-proprietary-java-classes for reasons why using sun packages is not a good idea.

**Comment by holger-arndt** [comment]
Thanks!
